theme: jekyll-theme-cayman

title: FSE
description: Welcome to the Web site of the ACM International Conference on the Foundations of Software Engineering (FSE)

repository: ESEC-FSE/ESEC-FSE.github.io

defaults:
  -
    scope:
      path: "pages"
    values:
      permalink: :basename

exclude: [CNAME, Gemfile, Gemfile.lock, README.md]
